name: Build and push Docker image

on: 
  push:
    branches: 
      - githubaction


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Build docker image
      - run: docker build . --tag blog:$(date +%s)

      - name: Publish to Registery
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: forbsey/go-github-actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}